# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Türkçe Yazılım Konatı
email: turkce-yazilim-konati@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Türkçe tabanlı yazılım programlama dilleri geliştirmek başta olmak üzere bir araya gelen kişilerin oluşturduğu bir kümeyiz.
  Her türlü yardım ve katkı için bizimle iletişime geçin.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://turkce-yazilim-konati.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  turkce-yazilim-konati
twitter_username: TurkceYazilim
instagram_adı: turkceyazilimkonati
facebook_adı: turkceyazilimkonati
facebook_grupadı: turkceyazilimkonati

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-get-json
  # https://github.com/brockfanning/jekyll-get-json

repository: turkce-yazilim-konati/turkce-yazilim-konati.github.io
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#dizin ayarlama
layouts_dir: _döşekler
data_dir: _veri

encoding: utf-8

jekyll_get_json:
  - data: volkantash
    json: 'https://api.github.com/users/volkantash'
  - data: team
    json: 'https://api.github.com/orgs/turkce-yazilim-konati/teams'
    